In [ ]:
#Multipurpose programming 
    #Automation 
    #Desktop/Web/Network
    #Data Analytics
    #Machine Learning/Data Science 
    #Artificial Intelligence/Deep Learning 
    #IoT Application 

# New Section

# New Section

In [ ]:
from random import * 
for i in range(0,10):
    print(randint(0,9),randint(0,9),randint(0,9),randint(0,9),randint(0,9),randint(0,9))

7 9 1 4 8 1
7 3 3 5 2 1
3 9 4 5 6 7
0 5 5 0 1 4
8 6 2 4 6 3
3 4 8 3 0 6
6 8 0 6 3 4
2 9 1 7 8 9
7 8 9 6 8 5
0 6 9 0 2 4


In [ ]:
#Identifier 
instructorname = 'Rahul'
INSTRUCTORNAME = 'Rohit'

In [ ]:
type(instructorname)

str

In [ ]:
INSTRUCTORNAME

'Rohit'

In [ ]:
sales = 150.5

In [ ]:
type(sales)

float

In [ ]:
quantity = 10 
type(quantity)

int

In [ ]:
a = sales>100

In [ ]:
type(a)

bool

In [ ]:
#Dynamically Typed Programming Language

In [ ]:
cust123 = 'John'

In [1]:
cust123

NameError: name 'cust123' is not defined

In [ ]:
cust123or = 'James'

In [ ]:
cust123or

'James'

In [ ]:
123cust = 'Rahul'

SyntaxError: invalid syntax (Temp/ipykernel_18904/479330729.py, line 1)

In [ ]:
$_cust = 'Rahul'

SyntaxError: invalid syntax (Temp/ipykernel_18904/1685698129.py, line 1)

In [ ]:
_cust

'Rahul'

In [ ]:
import keyword 
len(keyword.kwlist)

36

In [ ]:
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [ ]:
false = 'Rahul'

In [ ]:
false

'Rahul'

In [ ]:
#Collection Datatypes 
    #Lists 
    #Tuples 
    #Sets 
    #Dictionaries 

In [ ]:
ages = [21,23,43,23,22,34,33,23]

In [ ]:
type(ages)

list

In [ ]:
#It can be created using square bracket 
#Lists can support heterogeneous datatypes 
#Lists are mutable in nature

In [ ]:
list1=['A',10,10.5,True]

In [ ]:
type(list1)

list

In [ ]:
list1[3]

True

In [ ]:
list1[1:]

[10, 10.5, True]

In [ ]:
list1[2]=12.5

In [ ]:
list1

['A', 10, 12.5, True]

In [ ]:
#Tuples 
tuple1 = (21,'A',True, 10.5)

In [ ]:
type(tuple1)

tuple

In [ ]:
tuple1[0]=22

TypeError: 'tuple' object does not support item assignment

In [ ]:
set1 = {1,2,2,3,4,5,5,6,7,7,7}

In [ ]:
1 in set1

True

In [ ]:
set1[0]

TypeError: 'set' object is not subscriptable

In [ ]:
#Dictionaries 
stud_details = {'sid':[1,2,3,4,5,6], 'sname':['A','B','C','D','E','F'],'sregion':['N','S','W','E','N','N']}

In [ ]:
type(stud_details)

dict

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(stud_details)

sid sname sregion
0    1     A       N
1    2     B       S
2    3     C       W
3    4     D       E
4    5     E       N
5    6     F       N

In [ ]:
stud_details1 = {'sid':[1,2,3,4,5],'sname':['a','b','c','d','e'],'sregion':['n','w','e','s','s']}

In [ ]:
pd.DataFrame(stud_details1)

sid sname sregion
0    1     a       n
1    2     b       w
2    3     c       e
3    4     d       s
4    5     e       s

In [ ]:
sales = [3245,4434,4532,2342]
profit = [432,345,643,355]
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
for i in range(0,4):
    print(profit[i]/sales[i])

0.13312788906009246
0.07780784844384303
0.14187996469549868
0.1515798462852263


In [ ]:
list(range(0,4))

[0, 1, 2, 3]

In [ ]:
import numpy as np

In [ ]:
profit_array = np.array(profit)

In [ ]:
sales_array = np.array(sales)

In [ ]:
profit_array

array([432, 345, 643, 355])

In [ ]:
sales_array

array([3245, 4434, 4532, 2342])

In [ ]:
profit_array/sales_array

array([0.13312789, 0.07780785, 0.14187996, 0.15157985])

In [ ]:
np.sqrt(100)

10.0

In [ ]:
sales_us = [3432,4332,3415,3333]
sales_eu = [4322,3221,2212,3121]
sales_jp = [1212,2133,2212,1212]
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [ ]:
sales_matrix

array([[3432, 4332, 3415, 3333],
       [4322, 3221, 2212, 3121],
       [1212, 2133, 2212, 1212]])

In [ ]:
sales_matrix[2,2]

2212

In [ ]:
sales_matrix[1:3,1:3]

array([[3221, 2212],
       [2133, 2212]])

In [ ]:
sales_matrix.shape

(3, 4)

In [ ]:
profit_us = [3432,4332,3415,3333]
profit_eu = [4322,3221,2212,3121]
profit_jp = [1212,2133,2212,1212]
profit_matrix = np.array([profit_us,profit_eu,profit_jp])

In [ ]:
profit_matrix/sales_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
pd.DataFrame(sales_matrix,columns=['Q1','Q2','Q3','Q4'])

Q1    Q2    Q3    Q4
0  3432  4332  3415  3333
1  4322  3221  2212  3121
2  1212  2133  2212  1212

In [ ]:
np.mean(sales_matrix)

2846.4166666666665

In [ ]:
np.mean(sales_matrix,axis=1)

array([3628.  , 3219.  , 1692.25])

In [ ]:
np.mean(sales_matrix,axis=0)

array([2988.66666667, 3228.66666667, 2613.        , 2555.33333333])

In [ ]:
np.max(sales_matrix,axis=1)

array([4332, 4322, 2212])

In [ ]:
np.max(sales_matrix,axis=0)

array([4322, 4332, 3415, 3333])

In [ ]:
stud_details1 = {'sid':[1,2,3,4,5],'sname':[A,B,C,D,E],'sregion':[N,E,W,S,W]} 

In [ ]:
sales_matrix

array([[3432, 4332, 3415, 3333],
       [4322, 3221, 2212, 3121],
       [1212, 2133, 2212, 1212]])

In [ ]:
sales_matrix[1:3,1:3]

array([[3221, 2212],
       [2133, 2212]])

In [ ]:
#if and else 

marks = 55
if marks<35:
    print('You failed the exam')
elif marks>=35 and marks<=50:
    print('You got avg marks')
else:
    print('You passed the exam')

You passed the exam


In [ ]:
#For loops

In [ ]:
for i in 'Simpliv':
    print(i)

S
i
m
p
l
i
v


In [ ]:
sales = [1232,2344,5344,4322]
for i in sales:
    print(i*0.25)

308.0
586.0
1336.0
1080.5


In [ ]:
len(sales)

4

In [ ]:
profit

[432, 345, 643, 355]

In [ ]:
for i in range(0,len(sales)):
    print(profit[i]/sales[i])

0.35064935064935066
0.14718430034129693
0.12032185628742514
0.08213789912077742


In [ ]:
list(range(0,4))

[0, 1, 2, 3]

In [ ]:
coupoun = 5 
utilized = 0 
while utilized<coupoun:
    print('Total coupons left are:', coupoun-utilized)
    utilized = utilized+1
print('No copouns left')

Total coupons left are: 5
Total coupons left are: 4
Total coupons left are: 3
Total coupons left are: 2
Total coupons left are: 1
No copouns left


In [ ]:
number = -5
result = 1
if number<0:
    print('There is no factorial of negative number')
else:
    while number>=1:
        result = result*number
        number=number-1
    print(result)

There is no factorial of negative number


In [ ]:
#Pandas 
import os
os.getcwd()

'C:\\Users\\Rahul\\Desktop'

In [ ]:
os.chdir('C:\\Users\\Rahul\\Desktop')

In [ ]:
tips = pd.read_csv('tips.csv')

In [ ]:
type(tips)

pandas.core.frame.DataFrame

In [ ]:
pd.read_csv('tips.csv')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
len(tips)

244

In [ ]:
len(tips.columns)

7

In [ ]:
tips.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [ ]:
tips.tail(6)

total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
tips[(tips['smoker']=='No') & (tips['sex']=='Female')]

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
32        15.06  3.00  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
37        16.93  3.07  Female     No   Sat  Dinner     3
51        10.29  2.60  Female     No   Sun  Dinner     2
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
66        16.45  2.47  Female     No   Sat  Dinner     2
71        17.07  3.00  Female     No   Sat  Dinner     3
74        14.73  2.20  Female     No   Sat  Dinner     2
82        10.07  1.83  Female     No  Thur   Lunch     1
85        34.83  5.17  Female     No  Thur   Lunch     4
94        22.75  3.25  Female     No   Fri  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
114       25.71  4.00  Female     No   Sun  Dinner     3
115       17.31  3.50  Female     No   Sun  Dinner     2
117       10.65  1.50  Female     No  Thur   Lunch     2
118       12.43  1.80  Female     No  Thur   Lunch     2
119       24.08  2.92  Female     No  Thur   Lunch     4
121       13.42  1.68  Female     No  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
125       29.80  4.20  Female     No  Thur   Lunch     6
127       14.52  2.00  Female     No  Thur   Lunch     2
128       11.38  2.00  Female     No  Thur   Lunch     2
131       20.27  2.83  Female     No  Thur   Lunch     2
132       11.17  1.50  Female     No  Thur   Lunch     2
133       12.26  2.00  Female     No  Thur   Lunch     2
134       18.26  3.25  Female     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
136       10.33  2.00  Female     No  Thur   Lunch     2
137       14.15  2.00  Female     No  Thur   Lunch     2
139       13.16  2.75  Female     No  Thur   Lunch     2
140       17.47  3.50  Female     No  Thur   Lunch     2
143       27.05  5.00  Female     No  Thur   Lunch     6
144       16.43  2.30  Female     No  Thur   Lunch     2
145        8.35  1.50  Female     No  Thur   Lunch     2
146       18.64  1.36  Female     No  Thur   Lunch     3
147       11.87  1.63  Female     No  Thur   Lunch     2
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
158       13.39  2.61  Female     No   Sun  Dinner     2
162       16.21  2.00  Female     No   Sun  Dinner     3
223       15.98  3.00  Female     No   Fri   Lunch     3
238       35.83  4.67  Female     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
tips[(tips['smoker']=='No') | (tips['sex']=='Female')]

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[184 rows x 7 columns]

In [ ]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
tips.iloc[0:4,0:4]

total_bill   tip     sex smoker
0       16.99  1.01  Female     No
1       10.34  1.66    Male     No
2       21.01  3.50    Male     No
3       23.68  3.31    Male     No

In [ ]:
tips.iloc[[0,2,4],[0,2,4,6]]

total_bill     sex  day  size
0       16.99  Female  Sun     2
2       21.01    Male  Sun     3
4       24.59  Female  Sun     4